# Phase 5 — Dollar Impact Model
# File: src/05_dollar_impact_model.py
#
# Purpose:
#   Translate the Phase 4 statistical findings into business
#   dollar terms across three scenarios.
#
#   Scenario A — Observed (what actually happened in the data)
#   Scenario B — Optimistic (what if the promo had worked: 5pp lift)
#   Scenario C — Conservative (what if promo had a 2pp lift)
#
#   Then model the monthly and annual platform-level cost
#   at different new-user acquisition volumes.
#
#   This is the section that answers the CFO's question:
#   "How much money did we spend and what did we get back?"

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import duckdb
import warnings
warnings.filterwarnings('ignore')

# ---------------------------------------------------------------
# Load funnel data
# ---------------------------------------------------------------
con = duckdb.connect('data/ab_test.duckdb')
df  = con.execute("SELECT * FROM user_funnel").df()
con.close()

control   = df[df['experiment_group'] == 'control']
treatment = df[df['experiment_group'] == 'treatment']

# ---------------------------------------------------------------
# Observed metrics from Phase 4
# ---------------------------------------------------------------
DISCOUNT_COST       = 7.03   # avg discount per treatment user ($)
AVG_ORDER_VALUE     = 35.00  # platform average order value ($)
AVG_REORDER_VALUE   = 35.00  # avg reorder value (identical across groups)

rate_ctrl           = control['reordered_30d'].mean()
rate_trtm           = treatment['reordered_30d'].mean()
rev_ctrl_90d        = control['net_revenue_90d'].mean()
rev_trtm_90d        = treatment['net_revenue_90d'].mean()
orders_ctrl_90d     = control['reorders_in_90d'].mean()
orders_trtm_90d     = treatment['reorders_in_90d'].mean()

print("=" * 65)
print("PHASE 5: DOLLAR IMPACT MODEL")
print("=" * 65)
print(f"\nObserved baseline (control group):")
print(f"  30-day reorder rate:        {rate_ctrl*100:.2f}%")
print(f"  Avg reorders in 90 days:    {orders_ctrl_90d:.3f}")
print(f"  Avg net revenue per user:   ${rev_ctrl_90d:.2f}")
print(f"\nObserved treatment group:")
print(f"  30-day reorder rate:        {rate_trtm*100:.2f}%")
print(f"  Avg reorders in 90 days:    {orders_trtm_90d:.3f}")
print(f"  Avg net revenue per user:   ${rev_trtm_90d:.2f}")
print(f"  Avg discount cost:          ${DISCOUNT_COST:.2f}")
print(f"  Net revenue gap vs control: ${rev_trtm_90d - rev_ctrl_90d:.2f}")

# ---------------------------------------------------------------
# Scenario definitions
# ---------------------------------------------------------------
scenarios = {
    'A — Observed (null result)': {
        'reorder_lift_pp':    round((rate_trtm - rate_ctrl) * 100, 4),
        'extra_orders_user':  round(orders_trtm_90d - orders_ctrl_90d, 4),
        'description': 'What actually happened — no behavioral change',
        'color': '#e74c3c',
    },
    'B — Conservative (2pp lift)': {
        'reorder_lift_pp':    2.0,
        'extra_orders_user':  round(2.0/100 * 3, 3),
        'description': 'Promo drives modest improvement — borderline viable',
        'color': '#f39c12',
    },
    'C — Optimistic (5pp lift)': {
        'reorder_lift_pp':    5.0,
        'extra_orders_user':  round(5.0/100 * 3, 3),
        'description': 'Promo drives planned MDE — justifies rollout',
        'color': '#27ae60',
    },
}

# Monthly new user volumes to model across
user_volumes = [10_000, 50_000, 100_000, 500_000, 1_000_000]

print("\n" + "=" * 65)
print("SCENARIO DEFINITIONS")
print("=" * 65)
for name, s in scenarios.items():
    print(f"\n  {name}")
    print(f"    Reorder rate lift:     {s['reorder_lift_pp']:+.4f}pp")
    print(f"    Extra orders/user:     {s['extra_orders_user']:+.4f}")
    print(f"    Description:           {s['description']}")

# ---------------------------------------------------------------
# Per-user economics for each scenario
# ---------------------------------------------------------------
print("\n" + "=" * 65)
print("PER-USER ECONOMICS BY SCENARIO")
print("=" * 65)

per_user_results = []
for name, s in scenarios.items():
    # Revenue from extra reorders generated by promo
    extra_revenue = s['extra_orders_user'] * AVG_REORDER_VALUE
    # Net value = extra revenue generated minus discount cost
    net_value     = extra_revenue - DISCOUNT_COST
    # ROI = net value / discount cost
    roi           = net_value / DISCOUNT_COST * 100

    per_user_results.append({
        'Scenario':             name,
        'Reorder lift (pp)':    s['reorder_lift_pp'],
        'Extra orders/user':    round(s['extra_orders_user'], 4),
        'Extra revenue/user':   round(extra_revenue, 2),
        'Discount cost/user':   DISCOUNT_COST,
        'Net value/user ($)':   round(net_value, 2),
        'ROI (%)':              round(roi, 1),
    })

    print(f"\n  {name}")
    print(f"    Extra revenue generated: ${extra_revenue:.2f}/user")
    print(f"    Discount cost:           ${DISCOUNT_COST:.2f}/user")
    print(f"    Net value per user:      ${net_value:.2f}")
    print(f"    ROI:                     {roi:.1f}%")

per_user_df = pd.DataFrame(per_user_results)

# ---------------------------------------------------------------
# Platform-level monthly and annual impact
# ---------------------------------------------------------------
print("\n" + "=" * 65)
print("PLATFORM-LEVEL MONTHLY COST / GAIN BY SCENARIO AND VOLUME")
print("=" * 65)

platform_rows = []
for name, s in scenarios.items():
    extra_rev_user = s['extra_orders_user'] * AVG_REORDER_VALUE
    net_val_user   = extra_rev_user - DISCOUNT_COST
    for vol in user_volumes:
        monthly_impact  = net_val_user * vol
        annual_impact   = monthly_impact * 12
        total_disc_cost = DISCOUNT_COST * vol
        platform_rows.append({
            'Scenario':                  name,
            'Monthly new users':         vol,
            'Total discount cost/mo ($)': round(total_disc_cost, 0),
            'Net monthly impact ($)':     round(monthly_impact, 0),
            'Net annual impact ($)':      round(annual_impact, 0),
        })

platform_df = pd.DataFrame(platform_rows)

for name in scenarios:
    subset = platform_df[platform_df['Scenario'] == name]
    print(f"\n  {name}")
    print(subset[['Monthly new users',
                  'Total discount cost/mo ($)',
                  'Net monthly impact ($)',
                  'Net annual impact ($)']].to_string(index=False))

# ---------------------------------------------------------------
# Break-even analysis
# ---------------------------------------------------------------
print("\n" + "=" * 65)
print("BREAK-EVEN ANALYSIS")
print("=" * 65)

# What reorder rate lift is needed for the promo to break even?
# Break-even: extra_orders * AOV = discount_cost
# extra_orders = discount_cost / AOV
# extra_orders as fraction of users = extra_orders / avg_orders_per_user
breakeven_extra_orders = DISCOUNT_COST / AVG_REORDER_VALUE
breakeven_lift_pp      = breakeven_extra_orders / 3 * 100

print(f"\n  For the $7.03 discount to break even:")
print(f"  Each treatment user must generate {breakeven_extra_orders:.4f} "
      f"extra reorders")
print(f"  That requires a reorder rate lift of ~{breakeven_lift_pp:.2f}pp")
print(f"  Observed lift: {(rate_trtm - rate_ctrl)*100:+.4f}pp")
print(f"  Gap to break-even: {breakeven_lift_pp - (rate_trtm-rate_ctrl)*100:.2f}pp")
print(f"\n  Conclusion: The promo would need to drive a {breakeven_lift_pp:.2f}pp")
print(f"  reorder rate improvement to justify its cost. The observed")
print(f"  improvement was effectively zero.")

# ---------------------------------------------------------------
# Visualization: 3-panel dollar impact chart
# ---------------------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(17, 6))
fig.suptitle('Dollar Impact Model — 20% Promo A/B Test',
             fontsize=14, fontweight='bold')

scenario_names  = [s.split('—')[0].strip() for s in scenarios]
net_values      = [r['Net value/user ($)'] for r in per_user_results]
colors_bar      = [s['color'] for s in scenarios.values()]

# Panel 1: Net value per user by scenario
ax1 = axes[0]
bars = ax1.bar(scenario_names, net_values, color=colors_bar, alpha=0.88, width=0.5)
ax1.axhline(0, color='black', lw=1, ls='--')
ax1.set_ylabel('Net value per user ($)', fontsize=10)
ax1.set_title('Net Value per User\nby Scenario', fontsize=11)
for bar, val in zip(bars, net_values):
    ax1.text(bar.get_x() + bar.get_width()/2,
             val + (0.15 if val >= 0 else -0.35),
             f'${val:.2f}', ha='center', va='bottom',
             fontsize=10, fontweight='bold')
ax1.set_ylim(min(net_values) - 1.5, max(net_values) + 1.5)
ax1.grid(True, alpha=0.3, axis='y')
ax1.tick_params(axis='x', labelsize=8)

# Panel 2: Annual platform impact at 100K monthly new users
ax2 = axes[1]
vol_100k = platform_df[platform_df['Monthly new users'] == 100_000]
annual_impacts = []
for name in scenarios:
    row = vol_100k[vol_100k['Scenario'] == name]
    annual_impacts.append(row['Net annual impact ($)'].values[0])

bars2 = ax2.bar(scenario_names, annual_impacts,
                color=colors_bar, alpha=0.88, width=0.5)
ax2.axhline(0, color='black', lw=1, ls='--')
ax2.set_ylabel('Annual net impact ($)', fontsize=10)
ax2.set_title('Annual Platform Impact\n(100K new users/month)', fontsize=11)
ax2.yaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M' if abs(x) >= 1e6
                          else f'${x/1e3:.0f}K'))
for bar, val in zip(bars2, annual_impacts):
    label = (f'${val/1e6:.2f}M' if abs(val) >= 1e6
             else f'${val/1e3:.0f}K')
    ax2.text(bar.get_x() + bar.get_width()/2,
             val + (max(annual_impacts)*0.02 if val >= 0
                    else min(annual_impacts)*0.02),
             label, ha='center', va='bottom',
             fontsize=9, fontweight='bold')
ax2.grid(True, alpha=0.3, axis='y')
ax2.tick_params(axis='x', labelsize=8)

# Panel 3: Net monthly impact across user volumes (line chart)
ax3 = axes[2]
for name, s in scenarios.items():
    short = name.split('—')[0].strip()
    subset = platform_df[platform_df['Scenario'] == name]
    ax3.plot(subset['Monthly new users'],
             subset['Net monthly impact ($)'],
             color=s['color'], lw=2, marker='o',
             markersize=5, label=short)
ax3.axhline(0, color='black', lw=1, ls='--')
ax3.set_xlabel('Monthly new users acquiring promo', fontsize=10)
ax3.set_ylabel('Net monthly impact ($)', fontsize=10)
ax3.set_title('Monthly Impact vs. Acquisition Volume\nby Scenario', fontsize=11)
ax3.xaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x, _: f'{int(x/1000)}K'))
ax3.yaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x, _: f'${x/1e6:.1f}M' if abs(x) >= 1e6
                          else f'${x/1e3:.0f}K'))
ax3.legend(fontsize=9)
ax3.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('reports/dollar_impact_model.png', dpi=150, bbox_inches='tight')
plt.close()
print("\nSaved: reports/dollar_impact_model.png")

# ---------------------------------------------------------------
# Save all outputs
# ---------------------------------------------------------------
per_user_df.to_csv('reports/per_user_economics.csv', index=False)
platform_df.to_csv('reports/platform_impact_by_volume.csv', index=False)
print("Saved: reports/per_user_economics.csv")
print("Saved: reports/platform_impact_by_volume.csv")

# ---------------------------------------------------------------
# Final summary printout
# ---------------------------------------------------------------
print("\n" + "=" * 65)
print("PHASE 5 COMPLETE — KEY FINDINGS")
print("=" * 65)
print(f"""
  Scenario A (observed — null result):
    Net value per user:   ${per_user_results[0]['Net value/user ($)']:.2f}
    At 100K users/month:  ${per_user_results[0]['Net value/user ($)']*100000*12/1e6:.2f}M annual loss

  Scenario B (conservative — 2pp lift):
    Net value per user:   ${per_user_results[1]['Net value/user ($)']:.2f}
    At 100K users/month:  ${per_user_results[1]['Net value/user ($)']*100000*12/1e6:.2f}M annual loss

  Scenario C (optimistic — 5pp lift):
    Net value per user:   ${per_user_results[2]['Net value/user ($)']:.2f}
    At 100K users/month:  ${per_user_results[2]['Net value/user ($)']*100000*12/1e6:.2f}M annual gain

  Break-even reorder lift required: ~{breakeven_lift_pp:.2f}pp
  Observed lift:                     {(rate_trtm-rate_ctrl)*100:+.4f}pp

  The promo destroys value in observed and conservative scenarios.
  Only a 5pp+ lift makes it financially viable — and that lift
  was not observed in the data.

  Phase 6 will formalize this into the Go/No-Go recommendation.
""")
